### PR TITLE
CompatHelper + correction of indentation: 4-spaces per level

### PR DESCRIPTION
**Pull request by owinter92**
Dear Petr,

recently I took an interest in your package MeshCore. During the study of the code I took an additional time to hopefully made the code more clear in terms of formatting. Main changes: (i) consistent indentation (4-spaces per level) and (ii) formatting of the code in more native Julia way. Furthermore, I added CompatHelper, as I had a problem with StaticArray dependency due to recent update to 1.0.x.

Ondra

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
Nazdar Ondreji,

(doufam ze muzu tykat?). Doufam ze nebude vadit kdyz prejdu do anglictiny,
tu diktuju a cestinu bych musel datlovat.

On Sun, Feb 14, 2021 at 6:01 AM Ondřej Winter <notifications@github.com>
wrote:

> Dear Petr,
>
> recently I took an interest in your package MeshCore. During the study of
> the code I took an additional time to hopefully made the code more clear in
> terms of formatting. Main changes: (i) consistent indentation (4-spaces per
> level) and (ii) formatting of the code in more native Julia way.
> Furthermore, I added CompatHelper, as I had a problem with StaticArray
> dependency due to recent update to 1.0.x.
>
I have to admit that the code was developed with Sublime Text, which
handles
the formatting of the code for graphical display without user intervention
so that I never noticed
spurious tabs instead of proper spaces. Any improvements of the formatting
are
of course appreciated.

I would also appreciate any pointers as to the experience with the static
arrays.
I haven't had a chance to update packages that depend on them, so I am
at the moment blithely oblivious to any problems with an upgrade to 1.0.

Of course, I'm curious why this package was something you wished to look at.

Best regards,

P

>

**Comment by owinter92** [comment]
Ahoj,

jasne muzes, tak to jsem necekal. :D S anglictinou neni problem.

>I would also appreciate any pointers as to the experience with the static
arrays.
I haven't had a chance to update packages that depend on them, so I am
at the moment blithely oblivious to any problems with an upgrade to 1.0.

As far as I know there are none. Quick review of issues in StaticArrays repo shows that the last breaking-change was on Dec 22, 2019. The problem comes from my dependency in the project on 1.0.x, which is purely artificial because I start the project recently unaware of jump in StaticArray version and could be solved simply by adding ^0.12. I think the best approach for now is 
>[compat]
-StaticArrays = "^0.12"
+StaticArrays = "^0.12, 1.0"

in MeshCore's Project.toml file to ensure compatibility with the rest of your packages and move to ^1.0 later.

>Of course, I'm curious why this package was something you wished to look at.

For some time I am developing CFD solver based on the discontinuous Galerkin method (closed source for now) and as a long term project I am planning open the code. Of course with such a plan the inspection of the code is needed and naturally I started with my implementation of mesh. I have not yet gone through the rest of FinEtools system so I am not sure to what extent your packages serve my needs. However, during my inspection of the code it seemed worthwhile to push some changes.

PS: Is there a simple way to obtain ir(d1,d1,d2), for example elements mapped to neighboring elements through facets? 
PPS: Could you give me citation of the paper you are mentioning throughout MeshCore.

**Comment by PetrKryslUCSD** [comment]
FinEtools is actually not related to MeshCore. Contrariwise, https://github.com/PetrKryslUCSD/Elfel.jl is.

I'm not sure what you wish to accomplish, but I think it is to access elements on the other side of the facets
(either 2D or 3D). That is easily accomplished, for instance in 3D: build relation (3, 2), then transpose it to get
(2, 3). Now you can iterate the facets of your element with the first relation and use the second relation
to access the connected elements.

The paper is still under revision (frankly, it's been a nightmare: under review since mid-September :-( ).
Here is a copy: https://www.dropbox.com/s/6f69xml1h0g9xj1/ADES-S-20-00114.pdf?dl=0

**Comment by owinter92** [comment]
>FinEtools is actually not related to MeshCore. Contrariwise, https://github.com/PetrKryslUCSD/Elfel.jl is.

I see. I will check it out.

>I'm not sure what you wish to accomplish, but I think it is to access elements on the other side of the facets
(either 2D or 3D). That is easily accomplished, for instance in 3D: build relation (3, 2), then transpose it to get
(2, 3). Now you can iterate the facets of your element with the first relation and use the second relation
to access the connected elements.

Indeed. I figured this out. I was just checking if there is another way.

>Here is a copy: https://www.dropbox.com/s/6f69xml1h0g9xj1/ADES-S-20-00114.pdf?dl=0

Thanks.

**Pull request merged**
